### ISSUE TITLE
Timeline demo is empty

### ISSUE THREAD

**Issue by lahwran** [propublica/timeline-setter#38]
http://propublica.github.com/timeline-setter/doc/twitter-demo.html

there doesn't appear to be anything there.

**Comment by thejefflarson** [comment]
Fixed.

**Comment by lahwran** [comment]
I'm still getting the issue, even after a cache flush. this is what it looks like to me, if it's relevant: http://i.imgur.com/sgsgu.png
